#!/usr/bin/env bash
set -euo pipefail

use_monarch_helpers() {
  export MONARCH_PATH="/root/monarch"
  export MONARCH_INSTALL="/root/monarch/install"
  export MONARCH_INSTALL_LOG_FILE="/var/log/monarch-install.log"
  export OMARCHY_MIRROR="$(cat /root/omarchy_mirror)"
  source /root/monarch/install/helpers/all.sh
}

run_configurator() {
  set_tokyo_night_colors
  ./configurator
  export MONARCH_USER="$(jq -r '.users[0].username' user_credentials.json)"
}

install_arch() {
  clear_logo
  gum style --foreground 3 --padding "1 0 0 $PADDING_LEFT" "Installing..."
  echo

  touch /var/log/monarch-install.log

  start_log_output

  # Set CURRENT_SCRIPT for the trap to display better when nothing is returned for some reason
  CURRENT_SCRIPT="install_base_system"
  install_base_system 2>&1 | sed -u 's/\x1b\[[0-9;]*[a-zA-Z]//g' >>/var/log/monarch-install.log
  unset CURRENT_SCRIPT
  stop_log_output
}

install_monarch() {
  chroot_bash -lc "sudo pacman -S --noconfirm --needed gum" >/dev/null
  chroot_bash -lc "source /home/$MONARCH_USER/.local/share/monarch/install.sh || bash"

  # Reboot if requested by installer
  if [[ -f /mnt/var/tmp/monarch-install-completed ]]; then
    reboot
  fi
}

# Set Tokyo Night color scheme for the terminal
set_tokyo_night_colors() {
  if [[ $(tty) == "/dev/tty"* ]]; then
    # Tokyo Night color palette
    echo -en "\e]P01a1b26" # black (background)
    echo -en "\e]P1f7768e" # red
    echo -en "\e]P29ece6a" # green
    echo -en "\e]P3e0af68" # yellow
    echo -en "\e]P47aa2f7" # blue
    echo -en "\e]P5bb9af7" # magenta
    echo -en "\e]P67dcfff" # cyan
    echo -en "\e]P7a9b1d6" # white
    echo -en "\e]P8414868" # bright black
    echo -en "\e]P9f7768e" # bright red
    echo -en "\e]PA9ece6a" # bright green
    echo -en "\e]PBe0af68" # bright yellow
    echo -en "\e]PC7aa2f7" # bright blue
    echo -en "\e]PDbb9af7" # bright magenta
    echo -en "\e]PE7dcfff" # bright cyan
    echo -en "\e]PFc0caf5" # bright white (foreground)

    # Set default foreground and background
    echo -en "\033[0m"
    clear
  fi
}

install_base_system() {
  # Initialize and populate the keyring
  pacman-key --init
  pacman-key --populate archlinux
  pacman-key --populate monarch
  pacman-key --populate omarchy

  # Sync the offline database so pacman can find packages
  pacman -Sy --noconfirm

  # Ensure that no mounts exist from past install attempts
  findmnt -R /mnt >/dev/null && umount -R /mnt

  # Install using files generated by the ./configurator
  # Skip NTP and WKD sync since we're offline (keyring is pre-populated in ISO)
  archinstall \
    --config user_configuration.json \
    --creds user_credentials.json \
    --silent \
    --skip-ntp \
    --skip-wkd \
    --skip-wifi-check

  # After archinstall sets up the base system but before our installer runs,
  # we need to ensure the offline pacman.conf is in place
  cp /etc/pacman.conf /mnt/etc/pacman.conf

  # Mount the offline mirror so it's accessible in the chroot
  mkdir -p /mnt/var/cache/monarch/mirror/offline
  mount --bind /var/cache/monarch/mirror/offline /mnt/var/cache/monarch/mirror/offline

  # Mount the offline python directory so it's accessible in the chroot
  mkdir -p /mnt/var/cache/python/offline
  mount --bind /var/cache/python/offline /mnt/var/cache/python/offline

  # Mount the packages dir so it's accessible in the chroot
  mkdir -p /mnt/opt/packages
  mount --bind /opt/packages /mnt/opt/packages

  # No need to ask for sudo during the installation (monarch itself responsible for removing after install)
  mkdir -p /mnt/etc/sudoers.d
  cat >/mnt/etc/sudoers.d/99-monarch-installer <<EOF
root ALL=(ALL:ALL) NOPASSWD: ALL
%wheel ALL=(ALL:ALL) NOPASSWD: ALL
$MONARCH_USER ALL=(ALL:ALL) NOPASSWD: ALL
EOF
  chmod 440 /mnt/etc/sudoers.d/99-monarch-installer

  # Copy the local monarch repo to the user's home directory
  mkdir -p /mnt/home/$MONARCH_USER/.local/share/
  cp -r /root/monarch /mnt/home/$MONARCH_USER/.local/share/

  chown -R 1000:1000 /mnt/home/$MONARCH_USER/.local/

  # Ensure all necessary scripts are executable
  find /mnt/home/$MONARCH_USER/.local/share/monarch -type f -path "*/bin/*" -exec chmod +x {} \;
  chmod +x /mnt/home/$MONARCH_USER/.local/share/monarch/boot.sh 2>/dev/null || true
  chmod +x /mnt/home/$MONARCH_USER/.local/share/monarch/default/waybar/indicators/screen-recording.sh 2>/dev/null || true
}

chroot_bash() {
  HOME=/home/$MONARCH_USER \
    arch-chroot -u $MONARCH_USER /mnt/ \
    env MONARCH_CHROOT_INSTALL=1 \
    MONARCH_USER_NAME="$(<user_full_name.txt)" \
    MONARCH_USER_EMAIL="$(<user_email_address.txt)" \
    OMARCHY_MIRROR="$OMARCHY_MIRROR" \
    USER="$MONARCH_USER" \
    HOME="/home/$MONARCH_USER" \
    /bin/bash "$@"
}

if [[ $(tty) == "/dev/tty1" ]]; then
  use_monarch_helpers
  run_configurator
  install_arch
  install_monarch
fi
